export const TECHNIQUES = [
  "Bends 1",
  "Vibrato 1",
  "Slide 1",
  "Legatto 2",
  "Muted Legatto 2",
  "Hammer On 1",
  "Pull Off 1",
  "Octaves 1",
  "Pre bends 1",
  "Double Stops 2",
  "Slide Bends 2",
  "FingerPicking 2",
  "Alternate picking 2",
  "Enconomy Picking 3",
  "Tremolo Picking 2",
  "Hibrid Picking 3",
  "String Skyping 3",
  "Selective Picking 4",
  "Swybrid Picking 4",
  "Thump 4",
  "Tapping 2",
  "Double Tapping 4",
  "Pick Tapping 2",
  "Slide Tapping 2",
  "Sweep Picking 3",
  "Sweep Tapping 4",
  "Trills 2",
  "Rakes 1",
  "Natural Harmonics 1",
  "Artificial Harmonics 2",
  "Pinch Harmonics 3",
  "Tapping Harmonics 3",
  "Whammy Bends & Vibrato 3",
];
